const defaultTheme = require('tailwindcss/defaultTheme');

/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            colors: {
                "surface-bright": "#fbf9f5",
                "primary-fixed": "#bcf0ae",
                "error": "#ba1a1a",
                "on-surface-variant": "#42493e",
                "tertiary-fixed": "#f3e57b",
                "surface-container-high": "#eae8e4",
                "primary-fixed-dim": "#a1d494",
                "secondary-container": "#fed3c7",
                "on-tertiary": "#ffffff",
                "primary": "#154212",
                "on-error-container": "#93000a",
                "error-container": "#ffdad6",
                "outline-variant": "#c2c9bb",
                "on-error": "#ffffff",
                "tertiary": "#695f00",
                "outline": "#72796e",
                "on-primary-fixed-variant": "#23501e",
                "on-primary-fixed": "#002201",
                "on-background": "#1b1c1a",
                "inverse-primary": "#a1d494",
                "secondary-fixed": "#ffdbd0",
                "secondary-fixed-dim": "#e7bdb1",
                "on-primary-container": "#9dd090",
                "background": "#fbf9f5",
                "surface-container": "#efeeea",
                "on-tertiary-fixed-variant": "#4f4700",
                "on-secondary": "#ffffff",
                "surface-container-highest": "#e4e2de",
                "inverse-on-surface": "#f2f0ed",
                "on-secondary-fixed": "#2c160e",
                "on-secondary-container": "#795950",
                "secondary": "#77574d",
                "inverse-surface": "#30312e",
                "surface-tint": "#3b6934",
                "on-secondary-fixed-variant": "#5d4037",
                "surface-dim": "#dbdad6",
                "on-tertiary-container": "#474000",
                "on-tertiary-fixed": "#201c00",
                "primary-container": "#2d5a27",
                "tertiary-fixed-dim": "#d6c862",
                "tertiary-container": "#baad4a",
                "on-primary": "#ffffff",
                "surface-variant": "#e4e2de",
                "surface-container-lowest": "#ffffff",
                "surface-container-low": "#f5f3ef",
                "surface": "#fbf9f5",
                "on-surface": "#1b1c1a"
            },
            fontFamily: {
                "headline": ["Manrope", ...defaultTheme.fontFamily.sans],
                "body": ["Public Sans", ...defaultTheme.fontFamily.sans],
                "label": ["Public Sans", ...defaultTheme.fontFamily.sans],
                "sans": ['Nunito', ...defaultTheme.fontFamily.sans],
            },
        },
    },

    plugins: [require('@tailwindcss/forms')],
};
